Simple implementation of trackable resources
TwiN/k8s-ttl-controller pull request #104
Opened 2024-12-17 19:40 UTC by hiddenmarten

## Summary
https://github.com/TwiN/k8s-ttl-controller/issues/100

I've decided to go with simple implementation at first and take trackable resources from the environment variable.

## Checklist

- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [X] Updated documentation in `README.md`, if applicable.

2024-12-17 19:50 UTC, hiddenmarten commented
The next step is here.
https://github.com/TwiN/k8s-ttl-controller/issues/105

2024-12-19 03:37 UTC, TwiN requested changes
The `TRACKABLE_RESOURCES` environment variable name isn't really clear. What resources are you talking about here? API resources? actual resource names? Perhaps an environment variable name such as `API_RESOURCES_TO_WATCH` would make more sense, as it conveys what the environment variable is trying to do. 

Also, please add some documentation on how to use this feature.

2024-12-25 19:58 UTC, hiddenmarten commented
@TwiN It's ready for review :)

2025-01-03 02:11 UTC, TwiN approved these changes

2025-01-03 02:11 UTC, merged

2025-01-03 02:11 UTC, TwiN commented
Thank you for the contribution!